CREATE TABLE history_orders (
  id TEXT PRIMARY KEY,
  symbol TEXT,
  side TEXT,
  orderType TEXT,
  volume REAL,
  filledVolume REAL,
  limitPrice REAL,
  stopLossPrice REAL,
  avgFillPrice REAL,
  status TEXT,
  updatedAtText TEXT,
  parsedUpdatedAt TEXT,
  profit REAL,
  grossProfit REAL,
  swap REAL,
  commission REAL,
  orderId TEXT UNIQUE,
  importedAt TEXT NOT NULL,
  createdAt TEXT NOT NULL
);
